Fix examples structure of TS
lf-lang/playground-lingua-franca pull request #69
Opened 2023-07-22 23:44 UTC by hokeun

Fix https://github.com/lf-lang/playground-lingua-franca/issues/46

2023-07-22 23:49 UTC, lhstrh commented
These renames are not fully correct. Each project should have an src directory with the LF sources in it.

2023-07-22 23:54 UTC, hokeun commented
> These renames are not fully correct. Each project should have an src directory with the LF sources in it.

Let me know if it's correct now!

2023-07-23 01:17 UTC, lhstrh requested changes
Looks good except for two files that still need to be moved.

2023-07-23 01:17 UTC, lhstrh commented on examples/TypeScript/HTTPServerReactor/src/gcp/Dockerfile
This should be in `HTTPServerReactor/gcp/`.

2023-07-23 01:17 UTC, lhstrh commented on examples/TypeScript/HTTPServerReactor/src/gcp/README.md
This should be in `HTTPServerReactor/gcp/`.

2023-07-23 01:35 UTC, hokeun commented on examples/TypeScript/HTTPServerReactor/src/gcp/Dockerfile
Thanks, done.

2023-07-23 01:35 UTC, hokeun commented on examples/TypeScript/HTTPServerReactor/src/gcp/README.md
Thanks, done.

2023-07-23 06:23 UTC, lhstrh approved these changes
Perfect. Thanks, @hokeun!

2023-07-23 06:23 UTC, merged