Added illustrations of the CAL theorem
lf-lang/playground-lingua-franca pull request #87
Opened 2023-09-24 17:11 UTC by edwardalee

These examples show how to relax consistency to improve availability for both centralized and decentralized coordination.

2023-09-25 06:44 UTC, lhstrh requested changes
Nice! I added some feedback on the comments...

2023-09-25 06:44 UTC, lhstrh commented on examples/C/src/distributed/img/CALDecentralized.png
The images are identical (except for the name of the federated reactor). Why include two copies?

2023-09-25 06:44 UTC, lhstrh commented on examples/C/src/distributed/CALDecentralized.lf
> + * increase the STP offset in the `Actuate` reactor to get proper decentralized control. Any number
It's unclear what is meant by "proper decentralized control." The subsequent sentences sketch a trade-off, where tolerating inconsistency can be a perfectly proper choice if availability is considered more important.

2023-09-25 06:44 UTC, lhstrh commented on examples/C/src/distributed/CALDecentralized.lf
> + * (the deadline), then the coordinator can preserve availability at the expense of consistency.
It seems misleading to refer to an entity named "the coordinator" since this is about decentralized control.

2023-10-05 19:37 UTC, edwardalee commented on examples/C/src/distributed/img/CALDecentralized.png
The images are not quite the same. The names are important.

2023-10-05 20:04 UTC, lhstrh commented on examples/C/src/distributed/img/CALDecentralized.png
I don't understand. The only difference I see is the name of the main reactor. Am I overlooking something else? If the contents are identical, then what is the point in replicating the image? It doesn't relay any information besides the name of the image, which isn't needed if you don't have a second image.

2023-10-07 00:14 UTC, merged